# app/config/common/config_formatter.yml
ivory_ck_editor:
    default_config: my_config
    configs:
        my_config:
            language: '%locale%'
            toolbar:  [ ['Bold','Italic','Underline'], ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'], ['Link','Unlink'], ['Image'], ['Cut','Copy','Paste','-','Undo','Redo'], ['Maximize'] ]

        album_config:
            language: '%locale%'
            toolbar:  [ ['Bold','Italic','Underline'], ['Cut','Copy','Paste','-','Undo','Redo'], ['Maximize'] ]

        book_config:
            language: '%locale%'
            toolbar:  [ ['Bold','Italic','Underline'], ['Cut','Copy','Paste','-','Undo','Redo'], ['Maximize'] ]

sonata_formatter:
    formatters:
        richhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist

twig:
    form:
        resources:
            - 'SonataFormatterBundle:Form:formatter.html.twig'
