# app/config/common/config_vich.yml
twig:
    form_themes:
        - 'VichUploaderBundle:Form:fields.html.twig'

vich_uploader:
    db_driver: orm

    mappings:
        blog_images:
            uri_prefix:         /images/blog
            upload_destination: %kernel.root_dir%/../web/images/blog
            namer:              vich_uploader.namer_uniqid
            delete_on_remove:   true
            delete_on_update:   true

        album_cover:
            uri_prefix:         /images/albums_covers
            upload_destination: %kernel.root_dir%/../web/images/albums_covers
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     true
            delete_on_remove:   true
            delete_on_update:   true

        book_cover:
            uri_prefix:         /images/books_covers
            upload_destination: %kernel.root_dir%/../web/images/books_covers
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     true
            delete_on_remove:   true
            delete_on_update:   true

        picture:
            uri_prefix:         /images/pictures
            upload_destination: %kernel.root_dir%/../web/images/pictures
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     true
            delete_on_remove:   true
            delete_on_update:   true
